services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - db
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - nginx
      - db
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 443:443
    networks:
      - nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

networks:
  db:
    driver: bridge
  nginx:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/dcella-d/data/mariadb
      o : bind
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/dcella-d/data/wordpress
      o : bind