version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "443"
    networks:
      - nginx
    volumes:
      - ./nginx/nginx:/etc/nginx
    depends_on:
      - db

  wordpress:
    image: wordpress
    ports:
      - "9000"
    networks:
      - nginx
      - datab
    volumes:
      - ./trash/wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    ports:
      - "3306"
    networks:
      - datab
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
    volumes:
      - ./mariadb:/var/lib/mysql

networks:
  datab:
    driver: bridge
  nginx:
    driver: bridge